name: Build Youtube Revanced APK

on:
  push:
    branches:
      - main  # Adjust this based on your repository's main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq wget

    - name: Make script executable
      run: |
        chmod +x revanced_build.sh

    - name: Run the script (automatically input 'y')
      run: |
        yes y | ./revanced_build.sh

    - name: Copy artifacts for upload
      run: |
        cp revanced-cli-*.jar /github/workspace
        cp revanced-patches-*.jar /github/workspace
        cp revanced-integrations-*.apk /github/workspace
        cp revanced_*.apk /github/workspace

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: revanced-apk-artifacts  # Name of the artifact
        path: |
          revanced_*.apk
